<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>Connect.Domain</AssemblyName>
        <RootNamespace>Connect.Domain</RootNamespace>
    </PropertyGroup>
</Project>